service: studio-ghibli-database-api
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: us-east-1
  deploymentBucket: studio-ghibli-service
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
        - cloudwatch:*
        - dynamodb:*
      Resource: "arn:aws:dynamodb:us-east-1:*:*"

functions:
  graphql:
    handler: /src/infrastructure/lambda/index.js
    events:
      - http:
          path: graphql
          method: post
          cors: true