Resources:
  RegionTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.moviesTableName}
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: language
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
        - AttributeName: language
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: ${self:custom.tableThroughput}
        WriteCapacityUnits: ${self:custom.tableThroughput}
      GlobalSecondaryIndexes:
        - IndexName: language
          KeySchema:
            - AttributeName: language
              KeyType: HASH
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: ${self:custom.tableThroughput}
            WriteCapacityUnits: ${self:custom.tableThroughput}
